server:
  port: 8081

auth:
  token:
    issuer:
      urls:
        google: http://home-auth-service:8081/home/auth/google/validate/id-token
        home-stack-auth: http://home-auth-service:8081/home/auth/home/token/validate

flyway:
  baselineOnMigrate: true
  enabled: false
  locations: ~/test

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/home-stack
    username: root
    password: password
    driver-class-name:  com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size:  5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: true

iot:
  mqtt:
    broker:
      host: mosquitto-service
      port: 1883
      security:
        ca-cert-path: /etc/ca/mqtt-signer-ca.crt
        client-keystore-path: /etc/jks/keystore.jks