application:
  id: home-telemetry-svc

spring:
  application:
    name: home-telemetry-svc
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  profiles:
    active: devmysql
  lifecycle:
    timeout-per-shutdown-phase: 1m
server:
  servlet:
    context-path: /home/telemetry
  compression:
    enabled: true
    min-response-size: 2KB
  shutdown: graceful

web:
  cache-control:
    max-age: 30

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

iot:
  mqtt:
    broker:
      host: 192.168.1.201
      port: 31883
      auto-reconnect: true
      clean-state: false
      client-id: home-telemetry-svc
      connection-retry: 5
      connection-timeout: 120
      keep-alive: 120
      publish-qos: 0
      subscribe-qos: 0
      security:
        ca-cert-path: /Users/aloksingh/git/iot-home-stack/secret/mqtt-signer-ca.crt
        client-keystore-type: JKS
        client-keystore-path: /Users/aloksingh/git/iot-home-stack/secret/mqtt.client.home-telemetry-svc.jks
        client-keystore-password: ${KSPASSWORD}
    devices:
      esp32-general-purpose-1:
        name: ESP32 General Purpose Microcontroller 1
        type: esp32
        location: "JGTE Living Room"
        status-topic: home/alok/status/esp32-general-purpose-1
        command-topic: home/alok/command/esp32-general-purpose-1
        sensors:
          temperature:
            type: DHT11
            topic: home/alok/telemetry/temperature/esp32-general-purpose-1
          humidity:
            type: DHT11
            topic: home/alok/telemetry/humidity/esp32-general-purpose-1
      esp32-cam-1:
        name: ESP32 Camera Microcontroller 1
        type: esp32
        location: "JGTE Main Door"
        status-topic: home/alok/status/esp32-cam-1
        command-topic: home/alok/command/esp32-cam-1