application:
  id: home-telemetry-svc
spring:
  application:
    name: Telemetry Service
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  profiles:
    active: devmysql
  lifecycle:
    timeout-per-shutdown-phase: 1m
server:
  servlet:
    context-path: /home/telemetry
  compression:
    enabled: true
    min-response-size: 2KB
  shutdown: graceful

web:
  cache-control:
    max-age: 30
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
iot:
  mqtt:
    auto-reconnect: true
    clean-state: false
    client-id: alok
    connection-retry: 5
    connection-timeout: 120
    host: 192.168.1.201
    keep-alive: 120
    port: 31883
    publish-qos: 0
    publish-topic: home/stack/stmt-res
    status-topic: home/stack/status
    subscribe-qos: 0
    subscribe-topic: home/stack/stmt-req
  secure:
    keystore-file: keystore.jks
    keystore-password: ${KSPASSWORD}
    keystore-type: JKS
    truststore-file: truststore.jks
    truststore-password: ${TSPASSWORD}
